/********************************************************************************
** Form generated from reading UI file 'gamewindow.ui'
**
** Created by: Qt User Interface Compiler version 6.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAMEWINDOW_H
#define UI_GAMEWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GameWindow
{
public:
    QWidget *centralwidget;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QLabel *NomJoueur1;
    QLabel *NomJoueur2;
    QLabel *NomJoueur3;
    QLabel *NomJoueur4;
    QLabel *Carte3;
    QLabel *Carte2;
    QLabel *Carte1;
    QLCDNumber *NbJetonsBlanc;
    QLCDNumber *NbJetonsNoir;
    QLCDNumber *NbJetonsBleu;
    QLCDNumber *NbJetonsRouge;
    QLCDNumber *NbJetonsVert;
    QLCDNumber *NbJetonsOr;
    QLCDNumber *jetonsBlancJ1;
    QLCDNumber *jetonsNoirJ1;
    QLCDNumber *jetonsBleuJ1;
    QLCDNumber *jetonsRougeJ1;
    QLCDNumber *jetonsVertJ1;
    QLCDNumber *jetonsOrJ1;
    QLCDNumber *jetonsNoirJ2;
    QLCDNumber *jetonsBlancJ2;
    QLCDNumber *jetonsOrJ2;
    QLCDNumber *jetonsBleuJ2;
    QLCDNumber *jetonsRougeJ2;
    QLCDNumber *jetonsVertJ2;
    QWidget *gridLayoutWidget;
    QGridLayout *cartesPlateau;
    QPushButton *carte21;
    QPushButton *carte10;
    QSpacerItem *horizontalSpacer_2;
    QPushButton *carte12;
    QPushButton *carte01;
    QPushButton *carte00;
    QSpacerItem *verticalSpacer;
    QPushButton *carte11;
    QPushButton *carte20;
    QPushButton *carte02;
    QSpacerItem *horizontalSpacer;
    QSpacerItem *verticalSpacer_2;
    QPushButton *carte22;
    QPushButton *carte23;
    QPushButton *carte13;
    QPushButton *carte03;
    QLCDNumber *jetonsNoirJ3;
    QLCDNumber *jetonsRougeJ3;
    QLCDNumber *jetonsBlancJ3;
    QLCDNumber *jetonsOrJ3;
    QLCDNumber *jetonsVertJ3;
    QLCDNumber *jetonsBleuJ3;
    QLCDNumber *jetonsRougeJ4;
    QLCDNumber *jetonsVertJ4;
    QLCDNumber *jetonsBleuJ4;
    QLCDNumber *jetonsNoirJ4;
    QLCDNumber *jetonsBlancJ4;
    QLCDNumber *jetonsOrJ4;
    QLabel *Blanc1;
    QLabel *Noir1;
    QLabel *Bleu1;
    QLabel *Rouge1;
    QLabel *Vert1;
    QLabel *Or1;
    QLabel *Blanc2;
    QLabel *Rouge2;
    QLabel *Blanc3;
    QLabel *Rouge3;
    QLabel *Rouge4;
    QLabel *Blanc4;
    QLabel *Noir2;
    QLabel *Vert2;
    QLabel *Noir3;
    QLabel *Vert3;
    QLabel *Noir4;
    QLabel *Vert4;
    QLabel *Bleu2;
    QLabel *Or2;
    QLabel *Bleu3;
    QLabel *Or3;
    QLabel *Bleu4;
    QLabel *Or4;
    QLabel *label;
    QRadioButton *acheter;
    QRadioButton *reserver;
    QRadioButton *prendreJetons;
    QPushButton *finDeTour;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QLabel *label_2;
    QLabel *label_3;
    QFrame *cadreCartes4;
    QFrame *cadreCartes2;
    QFrame *cadreCartes3;
    QFrame *cadreCartes;
    QPushButton *JetonBlancPlateau;
    QPushButton *JetonNoirPlateau;
    QPushButton *JetonBleuPlateau;
    QPushButton *JetonRougePlateau;
    QPushButton *JetonVertPlateau;
    QPushButton *JetonOrPlateau;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *GameWindow)
    {
        if (GameWindow->objectName().isEmpty())
            GameWindow->setObjectName(QString::fromUtf8("GameWindow"));
        GameWindow->resize(1460, 800);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(151, 152, 155, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(226, 229, 233, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(188, 190, 194, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(75, 76, 78, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(100, 102, 103, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(203, 203, 205, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush9(QColor(0, 0, 0, 128));
        brush9.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        GameWindow->setPalette(palette);
        centralwidget = new QWidget(GameWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(1040, -20, 20, 811));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(1050, 180, 451, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(1050, 380, 461, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(1050, 570, 471, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        NomJoueur1 = new QLabel(centralwidget);
        NomJoueur1->setObjectName(QString::fromUtf8("NomJoueur1"));
        NomJoueur1->setGeometry(QRect(1150, 10, 211, 20));
        NomJoueur1->setAlignment(Qt::AlignCenter);
        NomJoueur2 = new QLabel(centralwidget);
        NomJoueur2->setObjectName(QString::fromUtf8("NomJoueur2"));
        NomJoueur2->setGeometry(QRect(1150, 200, 211, 20));
        NomJoueur2->setAlignment(Qt::AlignCenter);
        NomJoueur3 = new QLabel(centralwidget);
        NomJoueur3->setObjectName(QString::fromUtf8("NomJoueur3"));
        NomJoueur3->setGeometry(QRect(1150, 400, 211, 20));
        NomJoueur3->setAlignment(Qt::AlignCenter);
        NomJoueur4 = new QLabel(centralwidget);
        NomJoueur4->setObjectName(QString::fromUtf8("NomJoueur4"));
        NomJoueur4->setGeometry(QRect(1150, 590, 211, 20));
        NomJoueur4->setAlignment(Qt::AlignCenter);
        Carte3 = new QLabel(centralwidget);
        Carte3->setObjectName(QString::fromUtf8("Carte3"));
        Carte3->setGeometry(QRect(70, 200, 101, 151));
        Carte3->setPixmap(QPixmap(QString::fromUtf8("ressources/deck/3.png")));
        Carte3->setScaledContents(true);
        Carte2 = new QLabel(centralwidget);
        Carte2->setObjectName(QString::fromUtf8("Carte2"));
        Carte2->setGeometry(QRect(70, 380, 101, 151));
        Carte2->setPixmap(QPixmap(QString::fromUtf8("ressources/deck/2.png")));
        Carte2->setScaledContents(true);
        Carte1 = new QLabel(centralwidget);
        Carte1->setObjectName(QString::fromUtf8("Carte1"));
        Carte1->setGeometry(QRect(70, 560, 101, 151));
        Carte1->setPixmap(QPixmap(QString::fromUtf8("ressources/deck/1.png")));
        Carte1->setScaledContents(true);
        NbJetonsBlanc = new QLCDNumber(centralwidget);
        NbJetonsBlanc->setObjectName(QString::fromUtf8("NbJetonsBlanc"));
        NbJetonsBlanc->setGeometry(QRect(30, 110, 81, 41));
        NbJetonsNoir = new QLCDNumber(centralwidget);
        NbJetonsNoir->setObjectName(QString::fromUtf8("NbJetonsNoir"));
        NbJetonsNoir->setGeometry(QRect(130, 110, 81, 41));
        NbJetonsBleu = new QLCDNumber(centralwidget);
        NbJetonsBleu->setObjectName(QString::fromUtf8("NbJetonsBleu"));
        NbJetonsBleu->setGeometry(QRect(230, 110, 81, 41));
        NbJetonsRouge = new QLCDNumber(centralwidget);
        NbJetonsRouge->setObjectName(QString::fromUtf8("NbJetonsRouge"));
        NbJetonsRouge->setGeometry(QRect(330, 110, 81, 41));
        NbJetonsVert = new QLCDNumber(centralwidget);
        NbJetonsVert->setObjectName(QString::fromUtf8("NbJetonsVert"));
        NbJetonsVert->setGeometry(QRect(430, 110, 81, 41));
        NbJetonsOr = new QLCDNumber(centralwidget);
        NbJetonsOr->setObjectName(QString::fromUtf8("NbJetonsOr"));
        NbJetonsOr->setGeometry(QRect(530, 110, 81, 41));
        jetonsBlancJ1 = new QLCDNumber(centralwidget);
        jetonsBlancJ1->setObjectName(QString::fromUtf8("jetonsBlancJ1"));
        jetonsBlancJ1->setGeometry(QRect(1070, 50, 41, 41));
        jetonsBlancJ1->setDigitCount(1);
        jetonsBlancJ1->setSegmentStyle(QLCDNumber::Flat);
        jetonsNoirJ1 = new QLCDNumber(centralwidget);
        jetonsNoirJ1->setObjectName(QString::fromUtf8("jetonsNoirJ1"));
        jetonsNoirJ1->setGeometry(QRect(1210, 50, 41, 41));
        jetonsNoirJ1->setDigitCount(1);
        jetonsNoirJ1->setSegmentStyle(QLCDNumber::Flat);
        jetonsBleuJ1 = new QLCDNumber(centralwidget);
        jetonsBleuJ1->setObjectName(QString::fromUtf8("jetonsBleuJ1"));
        jetonsBleuJ1->setGeometry(QRect(1350, 50, 41, 41));
        jetonsBleuJ1->setDigitCount(1);
        jetonsBleuJ1->setSegmentStyle(QLCDNumber::Flat);
        jetonsRougeJ1 = new QLCDNumber(centralwidget);
        jetonsRougeJ1->setObjectName(QString::fromUtf8("jetonsRougeJ1"));
        jetonsRougeJ1->setGeometry(QRect(1070, 100, 41, 41));
        jetonsRougeJ1->setDigitCount(1);
        jetonsRougeJ1->setSegmentStyle(QLCDNumber::Flat);
        jetonsVertJ1 = new QLCDNumber(centralwidget);
        jetonsVertJ1->setObjectName(QString::fromUtf8("jetonsVertJ1"));
        jetonsVertJ1->setGeometry(QRect(1210, 100, 41, 41));
        jetonsVertJ1->setDigitCount(1);
        jetonsVertJ1->setSegmentStyle(QLCDNumber::Flat);
        jetonsOrJ1 = new QLCDNumber(centralwidget);
        jetonsOrJ1->setObjectName(QString::fromUtf8("jetonsOrJ1"));
        jetonsOrJ1->setGeometry(QRect(1350, 100, 41, 41));
        jetonsOrJ1->setDigitCount(1);
        jetonsOrJ1->setSegmentStyle(QLCDNumber::Flat);
        jetonsNoirJ2 = new QLCDNumber(centralwidget);
        jetonsNoirJ2->setObjectName(QString::fromUtf8("jetonsNoirJ2"));
        jetonsNoirJ2->setGeometry(QRect(1210, 240, 41, 41));
        jetonsNoirJ2->setDigitCount(1);
        jetonsNoirJ2->setSegmentStyle(QLCDNumber::Flat);
        jetonsBlancJ2 = new QLCDNumber(centralwidget);
        jetonsBlancJ2->setObjectName(QString::fromUtf8("jetonsBlancJ2"));
        jetonsBlancJ2->setGeometry(QRect(1070, 240, 41, 41));
        jetonsBlancJ2->setDigitCount(1);
        jetonsBlancJ2->setSegmentStyle(QLCDNumber::Flat);
        jetonsOrJ2 = new QLCDNumber(centralwidget);
        jetonsOrJ2->setObjectName(QString::fromUtf8("jetonsOrJ2"));
        jetonsOrJ2->setGeometry(QRect(1350, 290, 41, 41));
        jetonsOrJ2->setDigitCount(1);
        jetonsOrJ2->setSegmentStyle(QLCDNumber::Flat);
        jetonsBleuJ2 = new QLCDNumber(centralwidget);
        jetonsBleuJ2->setObjectName(QString::fromUtf8("jetonsBleuJ2"));
        jetonsBleuJ2->setGeometry(QRect(1350, 240, 41, 41));
        jetonsBleuJ2->setDigitCount(1);
        jetonsBleuJ2->setSegmentStyle(QLCDNumber::Flat);
        jetonsRougeJ2 = new QLCDNumber(centralwidget);
        jetonsRougeJ2->setObjectName(QString::fromUtf8("jetonsRougeJ2"));
        jetonsRougeJ2->setGeometry(QRect(1070, 290, 41, 41));
        jetonsRougeJ2->setDigitCount(1);
        jetonsRougeJ2->setSegmentStyle(QLCDNumber::Flat);
        jetonsVertJ2 = new QLCDNumber(centralwidget);
        jetonsVertJ2->setObjectName(QString::fromUtf8("jetonsVertJ2"));
        jetonsVertJ2->setGeometry(QRect(1210, 290, 41, 41));
        jetonsVertJ2->setDigitCount(1);
        jetonsVertJ2->setSegmentStyle(QLCDNumber::Flat);
        gridLayoutWidget = new QWidget(centralwidget);
        gridLayoutWidget->setObjectName(QString::fromUtf8("gridLayoutWidget"));
        gridLayoutWidget->setGeometry(QRect(180, 190, 568, 531));
        cartesPlateau = new QGridLayout(gridLayoutWidget);
        cartesPlateau->setObjectName(QString::fromUtf8("cartesPlateau"));
        cartesPlateau->setSizeConstraint(QLayout::SetDefaultConstraint);
        cartesPlateau->setContentsMargins(0, 0, 0, 0);
        carte21 = new QPushButton(gridLayoutWidget);
        carte21->setObjectName(QString::fromUtf8("carte21"));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(carte21->sizePolicy().hasHeightForWidth());
        carte21->setSizePolicy(sizePolicy);
        carte21->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon;
        icon.addFile(QString::fromUtf8("ressources/deck/3.png"), QSize(), QIcon::Normal, QIcon::Off);
        carte21->setIcon(icon);
        carte21->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte21, 0, 2, 1, 1);

        carte10 = new QPushButton(gridLayoutWidget);
        carte10->setObjectName(QString::fromUtf8("carte10"));
        carte10->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("ressources/deck/2.png"), QSize(), QIcon::Normal, QIcon::Off);
        carte10->setIcon(icon1);
        carte10->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte10, 2, 0, 1, 1);

        horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        cartesPlateau->addItem(horizontalSpacer_2, 0, 3, 1, 1);

        carte12 = new QPushButton(gridLayoutWidget);
        carte12->setObjectName(QString::fromUtf8("carte12"));
        carte12->setCursor(QCursor(Qt::OpenHandCursor));
        carte12->setIcon(icon1);
        carte12->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte12, 2, 4, 1, 1);

        carte01 = new QPushButton(gridLayoutWidget);
        carte01->setObjectName(QString::fromUtf8("carte01"));
        carte01->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("ressources/deck/1.png"), QSize(), QIcon::Normal, QIcon::Off);
        carte01->setIcon(icon2);
        carte01->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte01, 4, 2, 1, 1);

        carte00 = new QPushButton(gridLayoutWidget);
        carte00->setObjectName(QString::fromUtf8("carte00"));
        carte00->setCursor(QCursor(Qt::OpenHandCursor));
        carte00->setIcon(icon2);
        carte00->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte00, 4, 0, 1, 1);

        verticalSpacer = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);

        cartesPlateau->addItem(verticalSpacer, 1, 0, 1, 1);

        carte11 = new QPushButton(gridLayoutWidget);
        carte11->setObjectName(QString::fromUtf8("carte11"));
        carte11->setCursor(QCursor(Qt::OpenHandCursor));
        carte11->setIcon(icon1);
        carte11->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte11, 2, 2, 1, 1);

        carte20 = new QPushButton(gridLayoutWidget);
        carte20->setObjectName(QString::fromUtf8("carte20"));
        sizePolicy.setHeightForWidth(carte20->sizePolicy().hasHeightForWidth());
        carte20->setSizePolicy(sizePolicy);
        carte20->setCursor(QCursor(Qt::OpenHandCursor));
        carte20->setIcon(icon);
        carte20->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte20, 0, 0, 1, 1);

        carte02 = new QPushButton(gridLayoutWidget);
        carte02->setObjectName(QString::fromUtf8("carte02"));
        carte02->setCursor(QCursor(Qt::OpenHandCursor));
        carte02->setIcon(icon2);
        carte02->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte02, 4, 4, 1, 1);

        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        cartesPlateau->addItem(horizontalSpacer, 0, 1, 1, 1);

        verticalSpacer_2 = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);

        cartesPlateau->addItem(verticalSpacer_2, 3, 0, 1, 1);

        carte22 = new QPushButton(gridLayoutWidget);
        carte22->setObjectName(QString::fromUtf8("carte22"));
        sizePolicy.setHeightForWidth(carte22->sizePolicy().hasHeightForWidth());
        carte22->setSizePolicy(sizePolicy);
        carte22->setCursor(QCursor(Qt::OpenHandCursor));
        carte22->setIcon(icon);
        carte22->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte22, 0, 4, 1, 1);

        carte23 = new QPushButton(gridLayoutWidget);
        carte23->setObjectName(QString::fromUtf8("carte23"));
        sizePolicy.setHeightForWidth(carte23->sizePolicy().hasHeightForWidth());
        carte23->setSizePolicy(sizePolicy);
        carte23->setCursor(QCursor(Qt::OpenHandCursor));
        carte23->setIcon(icon);
        carte23->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte23, 0, 5, 1, 1);

        carte13 = new QPushButton(gridLayoutWidget);
        carte13->setObjectName(QString::fromUtf8("carte13"));
        carte13->setCursor(QCursor(Qt::OpenHandCursor));
        carte13->setIcon(icon1);
        carte13->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte13, 2, 5, 1, 1);

        carte03 = new QPushButton(gridLayoutWidget);
        carte03->setObjectName(QString::fromUtf8("carte03"));
        carte03->setCursor(QCursor(Qt::OpenHandCursor));
        carte03->setIcon(icon2);
        carte03->setIconSize(QSize(122, 169));

        cartesPlateau->addWidget(carte03, 4, 5, 1, 1);

        jetonsNoirJ3 = new QLCDNumber(centralwidget);
        jetonsNoirJ3->setObjectName(QString::fromUtf8("jetonsNoirJ3"));
        jetonsNoirJ3->setGeometry(QRect(1210, 440, 41, 41));
        jetonsNoirJ3->setDigitCount(1);
        jetonsNoirJ3->setSegmentStyle(QLCDNumber::Flat);
        jetonsRougeJ3 = new QLCDNumber(centralwidget);
        jetonsRougeJ3->setObjectName(QString::fromUtf8("jetonsRougeJ3"));
        jetonsRougeJ3->setGeometry(QRect(1070, 490, 41, 41));
        jetonsRougeJ3->setDigitCount(1);
        jetonsRougeJ3->setSegmentStyle(QLCDNumber::Flat);
        jetonsBlancJ3 = new QLCDNumber(centralwidget);
        jetonsBlancJ3->setObjectName(QString::fromUtf8("jetonsBlancJ3"));
        jetonsBlancJ3->setGeometry(QRect(1070, 440, 41, 41));
        jetonsBlancJ3->setDigitCount(1);
        jetonsBlancJ3->setSegmentStyle(QLCDNumber::Flat);
        jetonsOrJ3 = new QLCDNumber(centralwidget);
        jetonsOrJ3->setObjectName(QString::fromUtf8("jetonsOrJ3"));
        jetonsOrJ3->setGeometry(QRect(1350, 490, 41, 41));
        jetonsOrJ3->setDigitCount(1);
        jetonsOrJ3->setSegmentStyle(QLCDNumber::Flat);
        jetonsVertJ3 = new QLCDNumber(centralwidget);
        jetonsVertJ3->setObjectName(QString::fromUtf8("jetonsVertJ3"));
        jetonsVertJ3->setGeometry(QRect(1210, 490, 41, 41));
        jetonsVertJ3->setDigitCount(1);
        jetonsVertJ3->setSegmentStyle(QLCDNumber::Flat);
        jetonsBleuJ3 = new QLCDNumber(centralwidget);
        jetonsBleuJ3->setObjectName(QString::fromUtf8("jetonsBleuJ3"));
        jetonsBleuJ3->setGeometry(QRect(1350, 440, 41, 41));
        jetonsBleuJ3->setDigitCount(1);
        jetonsBleuJ3->setSegmentStyle(QLCDNumber::Flat);
        jetonsRougeJ4 = new QLCDNumber(centralwidget);
        jetonsRougeJ4->setObjectName(QString::fromUtf8("jetonsRougeJ4"));
        jetonsRougeJ4->setGeometry(QRect(1070, 680, 41, 41));
        jetonsRougeJ4->setDigitCount(1);
        jetonsRougeJ4->setSegmentStyle(QLCDNumber::Flat);
        jetonsVertJ4 = new QLCDNumber(centralwidget);
        jetonsVertJ4->setObjectName(QString::fromUtf8("jetonsVertJ4"));
        jetonsVertJ4->setGeometry(QRect(1210, 680, 41, 41));
        jetonsVertJ4->setDigitCount(1);
        jetonsVertJ4->setSegmentStyle(QLCDNumber::Flat);
        jetonsBleuJ4 = new QLCDNumber(centralwidget);
        jetonsBleuJ4->setObjectName(QString::fromUtf8("jetonsBleuJ4"));
        jetonsBleuJ4->setGeometry(QRect(1350, 630, 41, 41));
        jetonsBleuJ4->setDigitCount(1);
        jetonsBleuJ4->setSegmentStyle(QLCDNumber::Flat);
        jetonsNoirJ4 = new QLCDNumber(centralwidget);
        jetonsNoirJ4->setObjectName(QString::fromUtf8("jetonsNoirJ4"));
        jetonsNoirJ4->setGeometry(QRect(1210, 630, 41, 41));
        jetonsNoirJ4->setDigitCount(1);
        jetonsNoirJ4->setSegmentStyle(QLCDNumber::Flat);
        jetonsBlancJ4 = new QLCDNumber(centralwidget);
        jetonsBlancJ4->setObjectName(QString::fromUtf8("jetonsBlancJ4"));
        jetonsBlancJ4->setGeometry(QRect(1070, 630, 41, 41));
        jetonsBlancJ4->setDigitCount(1);
        jetonsBlancJ4->setSegmentStyle(QLCDNumber::Flat);
        jetonsOrJ4 = new QLCDNumber(centralwidget);
        jetonsOrJ4->setObjectName(QString::fromUtf8("jetonsOrJ4"));
        jetonsOrJ4->setGeometry(QRect(1350, 680, 41, 41));
        jetonsOrJ4->setDigitCount(1);
        jetonsOrJ4->setSegmentStyle(QLCDNumber::Flat);
        Blanc1 = new QLabel(centralwidget);
        Blanc1->setObjectName(QString::fromUtf8("Blanc1"));
        Blanc1->setGeometry(QRect(1120, 50, 41, 41));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(Blanc1->sizePolicy().hasHeightForWidth());
        Blanc1->setSizePolicy(sizePolicy1);
        Blanc1->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/blanc.png")));
        Blanc1->setScaledContents(true);
        Blanc1->setAlignment(Qt::AlignCenter);
        Noir1 = new QLabel(centralwidget);
        Noir1->setObjectName(QString::fromUtf8("Noir1"));
        Noir1->setGeometry(QRect(1260, 50, 41, 41));
        sizePolicy1.setHeightForWidth(Noir1->sizePolicy().hasHeightForWidth());
        Noir1->setSizePolicy(sizePolicy1);
        Noir1->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/noir.png")));
        Noir1->setScaledContents(true);
        Noir1->setAlignment(Qt::AlignCenter);
        Bleu1 = new QLabel(centralwidget);
        Bleu1->setObjectName(QString::fromUtf8("Bleu1"));
        Bleu1->setGeometry(QRect(1400, 50, 41, 41));
        sizePolicy1.setHeightForWidth(Bleu1->sizePolicy().hasHeightForWidth());
        Bleu1->setSizePolicy(sizePolicy1);
        Bleu1->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/bleu.png")));
        Bleu1->setScaledContents(true);
        Bleu1->setAlignment(Qt::AlignCenter);
        Rouge1 = new QLabel(centralwidget);
        Rouge1->setObjectName(QString::fromUtf8("Rouge1"));
        Rouge1->setGeometry(QRect(1120, 100, 41, 41));
        sizePolicy1.setHeightForWidth(Rouge1->sizePolicy().hasHeightForWidth());
        Rouge1->setSizePolicy(sizePolicy1);
        Rouge1->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/rouge.png")));
        Rouge1->setScaledContents(true);
        Rouge1->setAlignment(Qt::AlignCenter);
        Vert1 = new QLabel(centralwidget);
        Vert1->setObjectName(QString::fromUtf8("Vert1"));
        Vert1->setGeometry(QRect(1260, 100, 41, 41));
        sizePolicy1.setHeightForWidth(Vert1->sizePolicy().hasHeightForWidth());
        Vert1->setSizePolicy(sizePolicy1);
        Vert1->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/vert.png")));
        Vert1->setScaledContents(true);
        Vert1->setAlignment(Qt::AlignCenter);
        Or1 = new QLabel(centralwidget);
        Or1->setObjectName(QString::fromUtf8("Or1"));
        Or1->setGeometry(QRect(1400, 100, 41, 41));
        sizePolicy1.setHeightForWidth(Or1->sizePolicy().hasHeightForWidth());
        Or1->setSizePolicy(sizePolicy1);
        Or1->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/or.png")));
        Or1->setScaledContents(true);
        Or1->setAlignment(Qt::AlignCenter);
        Blanc2 = new QLabel(centralwidget);
        Blanc2->setObjectName(QString::fromUtf8("Blanc2"));
        Blanc2->setGeometry(QRect(1120, 240, 41, 41));
        sizePolicy1.setHeightForWidth(Blanc2->sizePolicy().hasHeightForWidth());
        Blanc2->setSizePolicy(sizePolicy1);
        Blanc2->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/blanc.png")));
        Blanc2->setScaledContents(true);
        Blanc2->setAlignment(Qt::AlignCenter);
        Rouge2 = new QLabel(centralwidget);
        Rouge2->setObjectName(QString::fromUtf8("Rouge2"));
        Rouge2->setGeometry(QRect(1120, 290, 41, 41));
        sizePolicy1.setHeightForWidth(Rouge2->sizePolicy().hasHeightForWidth());
        Rouge2->setSizePolicy(sizePolicy1);
        Rouge2->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/rouge.png")));
        Rouge2->setScaledContents(true);
        Rouge2->setAlignment(Qt::AlignCenter);
        Blanc3 = new QLabel(centralwidget);
        Blanc3->setObjectName(QString::fromUtf8("Blanc3"));
        Blanc3->setGeometry(QRect(1120, 440, 41, 41));
        sizePolicy1.setHeightForWidth(Blanc3->sizePolicy().hasHeightForWidth());
        Blanc3->setSizePolicy(sizePolicy1);
        Blanc3->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/blanc.png")));
        Blanc3->setScaledContents(true);
        Blanc3->setAlignment(Qt::AlignCenter);
        Rouge3 = new QLabel(centralwidget);
        Rouge3->setObjectName(QString::fromUtf8("Rouge3"));
        Rouge3->setGeometry(QRect(1120, 490, 41, 41));
        sizePolicy1.setHeightForWidth(Rouge3->sizePolicy().hasHeightForWidth());
        Rouge3->setSizePolicy(sizePolicy1);
        Rouge3->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/rouge.png")));
        Rouge3->setScaledContents(true);
        Rouge3->setAlignment(Qt::AlignCenter);
        Rouge4 = new QLabel(centralwidget);
        Rouge4->setObjectName(QString::fromUtf8("Rouge4"));
        Rouge4->setGeometry(QRect(1120, 680, 41, 41));
        sizePolicy1.setHeightForWidth(Rouge4->sizePolicy().hasHeightForWidth());
        Rouge4->setSizePolicy(sizePolicy1);
        Rouge4->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/rouge.png")));
        Rouge4->setScaledContents(true);
        Rouge4->setAlignment(Qt::AlignCenter);
        Blanc4 = new QLabel(centralwidget);
        Blanc4->setObjectName(QString::fromUtf8("Blanc4"));
        Blanc4->setGeometry(QRect(1120, 630, 41, 41));
        sizePolicy1.setHeightForWidth(Blanc4->sizePolicy().hasHeightForWidth());
        Blanc4->setSizePolicy(sizePolicy1);
        Blanc4->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/blanc.png")));
        Blanc4->setScaledContents(true);
        Blanc4->setAlignment(Qt::AlignCenter);
        Noir2 = new QLabel(centralwidget);
        Noir2->setObjectName(QString::fromUtf8("Noir2"));
        Noir2->setGeometry(QRect(1260, 240, 41, 41));
        sizePolicy1.setHeightForWidth(Noir2->sizePolicy().hasHeightForWidth());
        Noir2->setSizePolicy(sizePolicy1);
        Noir2->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/noir.png")));
        Noir2->setScaledContents(true);
        Noir2->setAlignment(Qt::AlignCenter);
        Vert2 = new QLabel(centralwidget);
        Vert2->setObjectName(QString::fromUtf8("Vert2"));
        Vert2->setGeometry(QRect(1260, 290, 41, 41));
        sizePolicy1.setHeightForWidth(Vert2->sizePolicy().hasHeightForWidth());
        Vert2->setSizePolicy(sizePolicy1);
        Vert2->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/vert.png")));
        Vert2->setScaledContents(true);
        Vert2->setAlignment(Qt::AlignCenter);
        Noir3 = new QLabel(centralwidget);
        Noir3->setObjectName(QString::fromUtf8("Noir3"));
        Noir3->setGeometry(QRect(1260, 440, 41, 41));
        sizePolicy1.setHeightForWidth(Noir3->sizePolicy().hasHeightForWidth());
        Noir3->setSizePolicy(sizePolicy1);
        Noir3->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/noir.png")));
        Noir3->setScaledContents(true);
        Noir3->setAlignment(Qt::AlignCenter);
        Vert3 = new QLabel(centralwidget);
        Vert3->setObjectName(QString::fromUtf8("Vert3"));
        Vert3->setGeometry(QRect(1260, 490, 41, 41));
        sizePolicy1.setHeightForWidth(Vert3->sizePolicy().hasHeightForWidth());
        Vert3->setSizePolicy(sizePolicy1);
        Vert3->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/vert.png")));
        Vert3->setScaledContents(true);
        Vert3->setAlignment(Qt::AlignCenter);
        Noir4 = new QLabel(centralwidget);
        Noir4->setObjectName(QString::fromUtf8("Noir4"));
        Noir4->setGeometry(QRect(1260, 630, 41, 41));
        sizePolicy1.setHeightForWidth(Noir4->sizePolicy().hasHeightForWidth());
        Noir4->setSizePolicy(sizePolicy1);
        Noir4->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/noir.png")));
        Noir4->setScaledContents(true);
        Noir4->setAlignment(Qt::AlignCenter);
        Vert4 = new QLabel(centralwidget);
        Vert4->setObjectName(QString::fromUtf8("Vert4"));
        Vert4->setGeometry(QRect(1260, 680, 41, 41));
        sizePolicy1.setHeightForWidth(Vert4->sizePolicy().hasHeightForWidth());
        Vert4->setSizePolicy(sizePolicy1);
        Vert4->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/vert.png")));
        Vert4->setScaledContents(true);
        Vert4->setAlignment(Qt::AlignCenter);
        Bleu2 = new QLabel(centralwidget);
        Bleu2->setObjectName(QString::fromUtf8("Bleu2"));
        Bleu2->setGeometry(QRect(1400, 240, 41, 41));
        sizePolicy1.setHeightForWidth(Bleu2->sizePolicy().hasHeightForWidth());
        Bleu2->setSizePolicy(sizePolicy1);
        Bleu2->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/bleu.png")));
        Bleu2->setScaledContents(true);
        Bleu2->setAlignment(Qt::AlignCenter);
        Or2 = new QLabel(centralwidget);
        Or2->setObjectName(QString::fromUtf8("Or2"));
        Or2->setGeometry(QRect(1400, 290, 41, 41));
        sizePolicy1.setHeightForWidth(Or2->sizePolicy().hasHeightForWidth());
        Or2->setSizePolicy(sizePolicy1);
        Or2->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/or.png")));
        Or2->setScaledContents(true);
        Or2->setAlignment(Qt::AlignCenter);
        Bleu3 = new QLabel(centralwidget);
        Bleu3->setObjectName(QString::fromUtf8("Bleu3"));
        Bleu3->setGeometry(QRect(1400, 440, 41, 41));
        sizePolicy1.setHeightForWidth(Bleu3->sizePolicy().hasHeightForWidth());
        Bleu3->setSizePolicy(sizePolicy1);
        Bleu3->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/bleu.png")));
        Bleu3->setScaledContents(true);
        Bleu3->setAlignment(Qt::AlignCenter);
        Or3 = new QLabel(centralwidget);
        Or3->setObjectName(QString::fromUtf8("Or3"));
        Or3->setGeometry(QRect(1400, 490, 41, 41));
        sizePolicy1.setHeightForWidth(Or3->sizePolicy().hasHeightForWidth());
        Or3->setSizePolicy(sizePolicy1);
        Or3->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/or.png")));
        Or3->setScaledContents(true);
        Or3->setAlignment(Qt::AlignCenter);
        Bleu4 = new QLabel(centralwidget);
        Bleu4->setObjectName(QString::fromUtf8("Bleu4"));
        Bleu4->setGeometry(QRect(1400, 630, 41, 41));
        sizePolicy1.setHeightForWidth(Bleu4->sizePolicy().hasHeightForWidth());
        Bleu4->setSizePolicy(sizePolicy1);
        Bleu4->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/bleu.png")));
        Bleu4->setScaledContents(true);
        Bleu4->setAlignment(Qt::AlignCenter);
        Or4 = new QLabel(centralwidget);
        Or4->setObjectName(QString::fromUtf8("Or4"));
        Or4->setGeometry(QRect(1400, 680, 41, 41));
        sizePolicy1.setHeightForWidth(Or4->sizePolicy().hasHeightForWidth());
        Or4->setSizePolicy(sizePolicy1);
        Or4->setPixmap(QPixmap(QString::fromUtf8("ressources/jetons/or.png")));
        Or4->setScaledContents(true);
        Or4->setAlignment(Qt::AlignCenter);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(860, 230, 111, 16));
        acheter = new QRadioButton(centralwidget);
        acheter->setObjectName(QString::fromUtf8("acheter"));
        acheter->setGeometry(QRect(840, 260, 161, 22));
        reserver = new QRadioButton(centralwidget);
        reserver->setObjectName(QString::fromUtf8("reserver"));
        reserver->setGeometry(QRect(840, 290, 161, 22));
        prendreJetons = new QRadioButton(centralwidget);
        prendreJetons->setObjectName(QString::fromUtf8("prendreJetons"));
        prendreJetons->setGeometry(QRect(840, 320, 161, 22));
        finDeTour = new QPushButton(centralwidget);
        finDeTour->setObjectName(QString::fromUtf8("finDeTour"));
        finDeTour->setGeometry(QRect(850, 360, 121, 31));
        finDeTour->setIconSize(QSize(121, 121));
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(808, 400, 211, 20));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(808, 210, 211, 20));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(800, 220, 16, 191));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralwidget);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(1010, 220, 16, 192));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralwidget);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(820, 40, 16, 71));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralwidget);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(982, 40, 16, 71));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralwidget);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(830, 100, 161, 20));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralwidget);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setGeometry(QRect(830, 30, 161, 20));
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(840, 50, 101, 16));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(860, 80, 111, 16));
        cadreCartes4 = new QFrame(centralwidget);
        cadreCartes4->setObjectName(QString::fromUtf8("cadreCartes4"));
        cadreCartes4->setGeometry(QRect(60, 730, 701, 20));
        cadreCartes4->setLineWidth(3);
        cadreCartes4->setFrameShape(QFrame::HLine);
        cadreCartes4->setFrameShadow(QFrame::Sunken);
        cadreCartes2 = new QFrame(centralwidget);
        cadreCartes2->setObjectName(QString::fromUtf8("cadreCartes2"));
        cadreCartes2->setGeometry(QRect(60, 160, 701, 20));
        cadreCartes2->setLineWidth(3);
        cadreCartes2->setFrameShape(QFrame::HLine);
        cadreCartes2->setFrameShadow(QFrame::Sunken);
        cadreCartes3 = new QFrame(centralwidget);
        cadreCartes3->setObjectName(QString::fromUtf8("cadreCartes3"));
        cadreCartes3->setGeometry(QRect(50, 170, 20, 571));
        cadreCartes3->setLineWidth(3);
        cadreCartes3->setFrameShape(QFrame::VLine);
        cadreCartes3->setFrameShadow(QFrame::Sunken);
        cadreCartes = new QFrame(centralwidget);
        cadreCartes->setObjectName(QString::fromUtf8("cadreCartes"));
        cadreCartes->setGeometry(QRect(750, 170, 20, 571));
        cadreCartes->setLineWidth(3);
        cadreCartes->setFrameShape(QFrame::VLine);
        cadreCartes->setFrameShadow(QFrame::Sunken);
        JetonBlancPlateau = new QPushButton(centralwidget);
        JetonBlancPlateau->setObjectName(QString::fromUtf8("JetonBlancPlateau"));
        JetonBlancPlateau->setGeometry(QRect(30, 20, 80, 81));
        JetonBlancPlateau->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("ressources/jetons/blanc.png"), QSize(), QIcon::Normal, QIcon::Off);
        JetonBlancPlateau->setIcon(icon3);
        JetonBlancPlateau->setIconSize(QSize(80, 81));
        JetonNoirPlateau = new QPushButton(centralwidget);
        JetonNoirPlateau->setObjectName(QString::fromUtf8("JetonNoirPlateau"));
        JetonNoirPlateau->setGeometry(QRect(130, 20, 80, 81));
        JetonNoirPlateau->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8("ressources/jetons/noir.png"), QSize(), QIcon::Normal, QIcon::Off);
        JetonNoirPlateau->setIcon(icon4);
        JetonNoirPlateau->setIconSize(QSize(80, 81));
        JetonBleuPlateau = new QPushButton(centralwidget);
        JetonBleuPlateau->setObjectName(QString::fromUtf8("JetonBleuPlateau"));
        JetonBleuPlateau->setGeometry(QRect(230, 20, 80, 81));
        JetonBleuPlateau->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8("ressources/jetons/bleu.png"), QSize(), QIcon::Normal, QIcon::Off);
        JetonBleuPlateau->setIcon(icon5);
        JetonBleuPlateau->setIconSize(QSize(80, 81));
        JetonRougePlateau = new QPushButton(centralwidget);
        JetonRougePlateau->setObjectName(QString::fromUtf8("JetonRougePlateau"));
        JetonRougePlateau->setGeometry(QRect(330, 20, 80, 81));
        JetonRougePlateau->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8("ressources/jetons/rouge.png"), QSize(), QIcon::Normal, QIcon::Off);
        JetonRougePlateau->setIcon(icon6);
        JetonRougePlateau->setIconSize(QSize(80, 81));
        JetonVertPlateau = new QPushButton(centralwidget);
        JetonVertPlateau->setObjectName(QString::fromUtf8("JetonVertPlateau"));
        JetonVertPlateau->setGeometry(QRect(430, 20, 80, 81));
        JetonVertPlateau->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8("ressources/jetons/vert.png"), QSize(), QIcon::Normal, QIcon::Off);
        JetonVertPlateau->setIcon(icon7);
        JetonVertPlateau->setIconSize(QSize(80, 81));
        JetonOrPlateau = new QPushButton(centralwidget);
        JetonOrPlateau->setObjectName(QString::fromUtf8("JetonOrPlateau"));
        JetonOrPlateau->setGeometry(QRect(530, 20, 80, 81));
        JetonOrPlateau->setCursor(QCursor(Qt::OpenHandCursor));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8("ressources/jetons/or.png"), QSize(), QIcon::Normal, QIcon::Off);
        JetonOrPlateau->setIcon(icon8);
        JetonOrPlateau->setIconSize(QSize(80, 81));
        GameWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(GameWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1460, 21));
        GameWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(GameWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        GameWindow->setStatusBar(statusbar);

        retranslateUi(GameWindow);

        QMetaObject::connectSlotsByName(GameWindow);
    } // setupUi

    void retranslateUi(QMainWindow *GameWindow)
    {
        GameWindow->setWindowTitle(QCoreApplication::translate("GameWindow", "MainWindow", nullptr));
        NomJoueur1->setText(QCoreApplication::translate("GameWindow", "NomJoueur1", nullptr));
        NomJoueur2->setText(QCoreApplication::translate("GameWindow", "NomJoueur2", nullptr));
        NomJoueur3->setText(QCoreApplication::translate("GameWindow", "NomJoueur3", nullptr));
        NomJoueur4->setText(QCoreApplication::translate("GameWindow", "NomJoueur4", nullptr));
        Carte3->setText(QString());
        Carte2->setText(QString());
        Carte1->setText(QString());
        carte21->setText(QString());
        carte10->setText(QString());
        carte12->setText(QString());
        carte01->setText(QString());
        carte00->setText(QString());
        carte11->setText(QString());
        carte20->setText(QString());
        carte02->setText(QString());
        carte22->setText(QString());
        carte23->setText(QString());
        carte13->setText(QString());
        carte03->setText(QString());
        Blanc1->setText(QString());
        Noir1->setText(QString());
        Bleu1->setText(QString());
        Rouge1->setText(QString());
        Vert1->setText(QString());
        Or1->setText(QString());
        Blanc2->setText(QString());
        Rouge2->setText(QString());
        Blanc3->setText(QString());
        Rouge3->setText(QString());
        Rouge4->setText(QString());
        Blanc4->setText(QString());
        Noir2->setText(QString());
        Vert2->setText(QString());
        Noir3->setText(QString());
        Vert3->setText(QString());
        Noir4->setText(QString());
        Vert4->setText(QString());
        Bleu2->setText(QString());
        Or2->setText(QString());
        Bleu3->setText(QString());
        Or3->setText(QString());
        Bleu4->setText(QString());
        Or4->setText(QString());
        label->setText(QCoreApplication::translate("GameWindow", "Action \303\240 r\303\251aliser :", nullptr));
        acheter->setText(QCoreApplication::translate("GameWindow", "Acheter une carte ", nullptr));
        reserver->setText(QCoreApplication::translate("GameWindow", "R\303\251server une carte ", nullptr));
        prendreJetons->setText(QCoreApplication::translate("GameWindow", "Prendre des jetons", nullptr));
        finDeTour->setText(QCoreApplication::translate("GameWindow", "Fin du tour ", nullptr));
        label_2->setText(QCoreApplication::translate("GameWindow", "Au tour de :", nullptr));
        label_3->setText(QCoreApplication::translate("GameWindow", "Joueur en cours", nullptr));
        JetonBlancPlateau->setText(QString());
        JetonNoirPlateau->setText(QString());
        JetonBleuPlateau->setText(QString());
        JetonRougePlateau->setText(QString());
        JetonVertPlateau->setText(QString());
        JetonOrPlateau->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class GameWindow: public Ui_GameWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAMEWINDOW_H
